### PR TITLE
feat: bump plug to version 1.0.1

### PR DESCRIPTION
**Pull request by eliassjogreen**

### CODE REVIEW

**Comment by DjDeveloperr** [comment]
The CI is failing with a weird error, try rebasing

**Comment by eliassjogreen** [comment]
@DjDeveloperr The current CI error seems to be because of a flaky test? I get this error locally sometime on my windows machine too when running the tests, even without the changes in this PR.

**Comment by DjDeveloperr** [comment]
Huh the CI on main seems to pass every time (I tried multiple runs) but never passed on the PR 🤔

**Comment by DjDeveloperr** [comment]
I'll look into this PR as soon as I find some time

**Comment by DjDeveloperr** [comment]
The problem is I can't reproduce this on my local Windows machine...

**Comment by DjDeveloperr** [comment]
I think I may have found the fix, try rebasing now

**Comment by DjDeveloperr** [comment]
Is the PR tested locally? The CI does not seem to test the plug actually downloading the binary.

**Comment by eliassjogreen** [comment]
Worked on my windows computer a week ago and when tested on a mac without sudo it gave a `PermissionDenied` error but otherwise worekd fine. I will look into this as it seems to be a plug issue with write permissions.

**Comment by eliassjogreen** [comment]
It was probably an issue before too, and there is a resolved similar issue in the plug repo from a little while ago.

**Review by DjDeveloperr — APPROVED** [review]
Oh, okay. Otherwise, LGTM! Thanks

**Pull request merged**
